#!/bin/bash
yum -y update
yum -y install httpd
echo "Hello Class" > /var/www/html/index.html
systemctl start httpd.service
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum -y install stress
echo "* * * * * /bin/stress -c 1 -t 58 >/dev/null 2>&1" > cron
crontab cron
