#!/bin/bash
# Install Apache Web Server and PHP
yum install -y httpd mysql 
amazon-linux-extras install -y php7.2 
# Download Lab files 
wget https://us-west-2-tcprod.s3.amazonaws.com/courses/ILT-TF-100-ARCHIT/v6.3.5/lab-2-webapp/scripts/inventory-app.zip 
unzip inventory-app.zip -d /var/www/html/ 
# Download and install the AWS SDK for PHP 
wget https://github.com/aws/aws-sdk-php/releases/download/3.62.3/aws.zip 
unzip aws -d /var/www/html
# Turn on web server 
chkconfig httpd on 
service httpd start
# Install Stress
yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 
yum install -y stress 
echo "* * * * * /bin/stress -c 1 -t 58 >/dev/null 2>&1" > cron
crontab cron
